apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
spec:
  containers:
    - name: nginx-privileged
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      securityContext:
        privileged: true
      resources:
        requests: # minimum resources required
          cpu: 250m
          memory: 64Mi
        limits: # maximum resources allocated
            cpu: 500m
            memory: 256Mi